services:
    metamodels.filter_register.factory:
        class: MetaModels\FilterRegisterBundle\FilterSetting\RegisterFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }
